# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='store',
            new_name='store_id',
        ),
    ]
